openapi: 3.2.0
info:
  version: 2.0.144
  title: Lichess.org API reference Challenges API
  contact:
    name: Lichess.org API
    url: https://lichess.org/api
    email: contact@lichess.org
  x-logo:
    url: https://lichess1.org/assets/logo/lichess-pad12.svg
  license:
    name: AGPL-3.0-or-later
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  description: '# Introduction

    Welcome to the reference for the Lichess API!'
servers:
- url: https://lichess.org
- url: https://lichess.dev
- url: http://localhost:{port}
  variables:
    port:
      default: '8080'
- url: http://l.org
tags:
- name: Challenges
  description: 'Send and receive challenges to play.


    To create a lot of challenges, consider bulk pairing instead.'
paths:
  /api/challenge:
    get:
      operationId: challengeList
      summary: List your challenges
      description: Get a list of challenges created by or targeted at you.
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:read
  /api/challenge/{username}:
    post:
      operationId: challengeCreate
      summary: Create a challenge
      description: 'Challenge someone to play. The targeted player can choose to accept or decline.

        If the challenge is accepted, you will be notified on the event stream

        that a new game has started. The game ID will be the same as the challenge ID.

        Challenges for realtime games (not correspondence) expire after 20s if not accepted.

        To prevent that, use the `keepAliveStream` flag described below.'
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
  /api/challenge/{challengeId}/show:
    get:
      operationId: challengeShow
      summary: Show one challenge
      description: Get details about a challenge, even if it has been recently accepted, canceled or declined.
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:read
  /api/challenge/{challengeId}/accept:
    post:
      operationId: challengeAccept
      summary: Accept a challenge
      description: 'Accept an incoming challenge.

        You should receive a `gameStart` event on the incoming events stream.'
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
  /api/challenge/{challengeId}/decline:
    post:
      operationId: challengeDecline
      summary: Decline a challenge
      description: Decline an incoming challenge.
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
  /api/challenge/{challengeId}/cancel:
    post:
      operationId: challengeCancel
      summary: Cancel a challenge
      description: 'Cancel a challenge you sent, or aborts the game if the challenge was accepted, but the game was not yet played.

        Note that the ID of a game is the same as the ID of the challenge that created it.

        Works for user challenges and open challenges alike.'
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
  /api/challenge/ai:
    post:
      operationId: challengeAi
      summary: Challenge the AI
      description: 'Start a game with Lichess AI.

        You will be notified on the event stream that a new game has started.'
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
        - bot:play
        - board:play
  /api/challenge/open:
    post:
      operationId: challengeOpen
      summary: Open-ended challenge
      description: 'Create a challenge that any 2 players can join.

        Share the URL of the challenge. the first 2 players to click it will be paired for a game.

        The response body also contains `whiteUrl` and `blackUrl`.

        You can control which color each player gets by giving them these URLs,

        instead of the main challenge URL.

        Open challenges expire after 24h.

        If the challenge creation is authenticated with OAuth2,

        then you can use the challenge cancel endpoint to cancel it.

        To directly pair 2 known players, use this endpoint instead.'
      tags:
      - Challenges
      security: []
  /api/challenge/{gameId}/start-clocks:
    post:
      operationId: challengeStartClocks
      summary: Start clocks of a game
      description: 'Start the clocks of a game immediately, even if a player has not yet made a move.

        Requires the OAuth tokens of both players with `challenge:write` scope.

        If the clocks have already started, the call will have no effect.


        For AI games with only one player, omit the `token2` parameter.'
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
  /api/round/{gameId}/add-time/{seconds}:
    post:
      operationId: roundAddTime
      summary: Add time to the opponent clock
      description: Add seconds to the opponent's clock. Can be used to create games with time odds.
      tags:
      - Challenges
      security:
      - OAuth2:
        - challenge:write
  /api/token/admin-challenge:
    post:
      operationId: adminChallengeTokens
      summary: Admin challenge tokens
      description: '**This endpoint can only be used by Lichess administrators. It will not work if you do not have the appropriate permissions.** Tournament organizers should instead use OAuth to obtain `challenge:write` tokens from users in order to perform bulk pairing.*

        Create and obtain `challenge:write` tokens for multiple users.

        If a similar token already exists for a user, it is reused. This endpoint is idempotent.'
      tags:
      - Challenges
      security:
      - OAuth2:
        - web:mod
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: 'Read [the introduction for how to make authenticated requests](#description/authentication).

        '
      flows:
        authorizationCode:
          authorizationUrl: https://lichess.org/oauth
          tokenUrl: https://lichess.org/api/token
          scopes:
            preference:read: Read your preferences
            preference:write: Write your preferences
            email:read: Read your email address
            engine:read: Read your external engines
            engine:write: Create, update, delete your external engines
            challenge:read: Read incoming challenges
            challenge:write: Create, accept, decline challenges
            challenge:bulk: Create, delete, query bulk pairings
            study:read: Read private studies and broadcasts
            study:write: Create, update, delete studies and broadcasts
            tournament:write: Create tournaments
            racer:write: Create and join puzzle races
            puzzle:read: Read puzzle activity
            puzzle:write: Write puzzle activity
            team:read: Read private team information
            team:write: Join, leave teams
            team:lead: Manage teams (kick members, send PMs)
            follow:read: Read followed players
            follow:write: Follow and unfollow other players
            msg:write: Send private messages to other players
            board:play: Play with the Board API
            bot:play: Play with the Bot API. Only for [Bot accounts](#tag/bot/POST/api/bot/account/upgrade)
            web:mod: Use moderator tools (within the bounds of your permissions)
