openapi: 3.2.0
info:
  version: 2.0.144
  title: Lichess.org API reference Board API
  contact:
    name: Lichess.org API
    url: https://lichess.org/api
    email: contact@lichess.org
  x-logo:
    url: https://lichess1.org/assets/logo/lichess-pad12.svg
  license:
    name: AGPL-3.0-or-later
    url: https://www.gnu.org/licenses/agpl-3.0.txt
  description: '# Introduction

    Welcome to the reference for the Lichess API!'
servers:
- url: https://lichess.org
- url: https://lichess.dev
- url: http://localhost:{port}
  variables:
    port:
      default: '8080'
- url: http://l.org
tags:
- name: Board
  description: Play on Lichess with physical boards and third-party clients.
paths:
  /api/stream/event:
    get:
      operationId: apiStreamEvent
      summary: Stream incoming events
      description: 'Stream the events reaching a lichess user in real time as ndjson.


        An empty line is sent every 7 seconds for keep alive purposes.


        Each non-empty line is a JSON object containing a `type` field. Possible values are:

        - `gameStart` Start of a game

        - `gameFinish` Completion of a game

        - `challenge` A player sends you a challenge or you challenge someone

        - `challengeCanceled` A player cancels their challenge to you

        - `challengeDeclined` The opponent declines your challenge


        When the stream opens, all current challenges and games are sent.


        Only one global event stream can be active at a time. When the stream opens, the previous one with the same access token is closed.'
      tags:
      - Board
      security:
      - OAuth2:
        - challenge:read
        - bot:play
        - board:play
  /api/board/seek:
    post:
      operationId: apiBoardSeek
      summary: Create a seek
      description: 'Create a public seek, to start a game with a random player.


        ### Real-time seek


        Specify the `time` and `increment` clock values.

        The response is streamed but doesn''t contain any information.


        **Keep the connection open to keep the seek active**.


        If the client closes the connection, the seek is canceled. This way, if the client terminates, the user won''t be paired in a game they wouldn''t play.

        When the seek is accepted, or expires, the server closes the connection.


        **Make sure to also have an Event stream open**, to be notified when a game starts.

        We recommend opening the Event stream first, then the seek stream. This way,

        you won''t miss the game event if the seek is accepted immediately.


        ### Correspondence seek


        Specify the `days` per turn value.

        The response is not streamed, it immediately completes with the seek ID. The seek remains active on the server until it is joined by someone.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/stream/{gameId}:
    get:
      operationId: boardGameStream
      summary: Stream Board game state
      description: 'Stream the state of a game being played with the Board API, as ndjson.


        Use this endpoint to get updates about the game in real-time, with a single request.


        Each line is a JSON object containing a `type` field. Possible values are:

        - `gameFull` Full game data. All values are immutable, except for the `state` field.

        - `gameState` Current state of the game. Immutable values not included. Sent when a move is played, a draw is offered, or when the game ends.

        - `chatLine` Chat message sent by a user in the `room` "player" or "spectator".

        - `opponentGone` Whether the opponent has left the game, and how long before you can claim a win or draw.


        The first line is always of type `gameFull`.


        The server closes the stream when the game ends, or if the game has already ended.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/move/{move}:
    post:
      operationId: boardGameMove
      summary: Make a Board move
      description: 'Make a move in a game being played with the Board API.

        The move can also contain a draw offer/agreement.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/chat:
    post:
      operationId: boardGameChatPost
      summary: Write in the chat
      description: Post a message to the player or spectator chat, in a game being played with the Board API.
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
    get:
      operationId: boardGameChatGet
      summary: Fetch the player chat
      description: 'Get the messages posted in the private game chat, i.e. the chat between the 2 players of the game.


        Games can also have a public spectator chat.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/abort:
    post:
      operationId: boardGameAbort
      summary: Abort a game
      description: Abort a game being played with the Board API.
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/resign:
    post:
      operationId: boardGameResign
      summary: Resign a game
      description: Resign a game being played with the Board API.
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/draw/{accept}:
    post:
      operationId: boardGameDraw
      summary: Handle draw offers
      description: 'Create/accept/decline draw offers.

        - `yes`: Offer a draw, or accept the opponent''s draw offer.

        - `no`: Decline a draw offer from the opponent.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/takeback/{accept}:
    post:
      operationId: boardGameTakeback
      summary: Handle takeback offers
      description: 'Create/accept/decline takebacks.

        - `yes`: Propose a takeback, or accept the opponent''s takeback offer.

        - `no`: Decline a takeback offer from the opponent.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/claim-victory:
    post:
      operationId: boardGameClaimVictory
      summary: Claim victory of a game
      description: Claim victory when the opponent has left the game for a while.
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/claim-draw:
    post:
      operationId: boardGameClaimDraw
      summary: Claim draw of a game
      description: Claim draw when the opponent has left the game for a while.
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
  /api/board/game/{gameId}/berserk:
    post:
      operationId: boardGameBerserk
      summary: Berserk a tournament game
      description: 'Go berserk on an arena tournament game. Halves the clock time, grants an extra point upon winning.

        Only available in arena tournaments that allow berserk, and before each player has made a move.'
      tags:
      - Board
      security:
      - OAuth2:
        - board:play
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: 'Read [the introduction for how to make authenticated requests](#description/authentication).

        '
      flows:
        authorizationCode:
          authorizationUrl: https://lichess.org/oauth
          tokenUrl: https://lichess.org/api/token
          scopes:
            preference:read: Read your preferences
            preference:write: Write your preferences
            email:read: Read your email address
            engine:read: Read your external engines
            engine:write: Create, update, delete your external engines
            challenge:read: Read incoming challenges
            challenge:write: Create, accept, decline challenges
            challenge:bulk: Create, delete, query bulk pairings
            study:read: Read private studies and broadcasts
            study:write: Create, update, delete studies and broadcasts
            tournament:write: Create tournaments
            racer:write: Create and join puzzle races
            puzzle:read: Read puzzle activity
            puzzle:write: Write puzzle activity
            team:read: Read private team information
            team:write: Join, leave teams
            team:lead: Manage teams (kick members, send PMs)
            follow:read: Read followed players
            follow:write: Follow and unfollow other players
            msg:write: Send private messages to other players
            board:play: Play with the Board API
            bot:play: Play with the Bot API. Only for [Bot accounts](#tag/bot/POST/api/bot/account/upgrade)
            web:mod: Use moderator tools (within the bounds of your permissions)
